<a href="https://colab.research.google.com/github/vanessaleija2025-png/LEIJA-CARDENAS-FATIMA-VANESSA---IVAN-SANCHEZ-FLORES-/blob/main/unidad_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# Importa la librería numpy para operaciones numéricas.
import numpy as np
# Define el array de valores de entrada x.
x = np.array([1,2,3])
# Define el array de valores de salida y.
y = np.array([1,4,9])

# Obtiene el número de puntos de datos.
n = len(x)

# Inicializa una matriz (tabla) de ceros para almacenar las diferencias divididas.
tabla = np.zeros((n,n))

# Copia los valores de y en la primera columna de la tabla.
tabla[:,0] = y

# Bucle anidado para calcular las diferencias divididas.
# El bucle exterior itera sobre las columnas de la tabla (orden de la diferencia).
for j in range(1,n):
  # El bucle interior itera sobre las filas (elementos de la diferencia).
  for i in range(n-j):
    # Calcula la diferencia dividida actual usando la fórmula de Newton.
    tabla[i,j] = (tabla[i+1,j-1] - tabla[i,j-1]) / (x[i+j] - x[i])

# Imprime la tabla de diferencias divididas resultante.
print("Tabla de diferencias divididas:\n",tabla)

Tabla de diferencias divididas:
 [[1. 3. 1.]
 [4. 5. 0.]
 [9. 0. 0.]]


In [11]:
# Importa la librería numpy para operaciones numéricas.
import numpy as np

# Define el array de valores de entrada x.
x = np.array([1, 2, 3])
# Define el array de valores de salida y.
y = np.array([1, 4, 9])

# Obtiene el número de puntos de datos.
n = len(x)

# Inicializa una matriz (tabla) de ceros para almacenar las diferencias divididas.
tabla = np.zeros((n, n))

# Copia los valores de y en la primera columna de la tabla.
tabla[:, 0] = y

# Bucle anidado para calcular las diferencias divididas.
for j in range(1, n):
    for i in range(n - j):
        # Calcula la diferencia dividida actual.
        tabla[i, j] = (tabla[i+1, j-1] - tabla[i, j-1]) / (x[i+j] - x[i])

# Define la función `newton_eval` para evaluar el polinomio interpolador de Newton.
def newton_eval(x_data, tabla, x_val):
    # Obtiene el número de puntos de datos.
    n = len(x_data)
    # Inicializa el resultado con el primer término de la tabla.
    resultado = tabla[0, 0]

    # Inicializa el producto para los términos (x_val - x_i).
    producto = 1

    # Itera para sumar los términos restantes del polinomio de Newton.
    for i in range(1, n):
        # Actualiza el producto acumulativo.
        producto *= (x_val - x_data[i-1])
        # Suma el término actual al resultado.
        resultado += tabla[0, i] * producto

    # Retorna el valor interpolado.
    return resultado

# Llama a la función `newton_eval` para interpolar en x_val = 2.5.
valor = newton_eval(x, tabla, 2.5)

# Imprime el valor interpolado.
print("Valor interpolado:", valor)

Valor interpolado: 6.25


In [12]:
# Importa la librería numpy para operaciones numéricas.
import numpy as np

# Define el array de valores de entrada x.
x = np.array([0,1,2,3])
# Define el array de valores de salida y.
y = np.array([1,2,0,5])

# Obtiene el número de puntos de datos.
n = len(x)

# Inicializa una matriz (tabla) de ceros para almacenar las diferencias divididas.
tabla = np.zeros((n, n))

# Copia los valores de y en la primera columna de la tabla.
tabla[:, 0] = y

# Bucle anidado para calcular las diferencias divididas.
for j in range(1, n):
    for i in range(n - j):
        # Calcula la diferencia dividida actual.
        tabla[i, j] = (tabla[i+1, j-1] - tabla[i, j-1]) / (x[i+j] - x[i])

# Define la función `newton` para evaluar el polinomio interpolador de Newton.
def newton(x_data, tabla, x_val):
    # Obtiene el número de puntos de datos.
    n = len(x_data)
    # Inicializa el resultado con el primer término de la tabla.
    resultado = tabla[0, 0]
    # Inicializa el producto para los términos (x_val - x_i).
    producto = 1

    # Itera para sumar los términos restantes del polinomio de Newton.
    for i in range(1, n):
        # Actualiza el producto acumulativo.
        producto *= (x_val - x_data[i-1])
        # Suma el término actual al resultado.
        resultado += tabla[0, i] * producto

    # Retorna el valor interpolado.
    return resultado

# Define el punto en el que se desea interpolar.
x_interp = 1.5

# Llama a la función `newton` para obtener el valor interpolado.
y_interp = newton(x,tabla,x_interp)

# Imprime el valor estimado (interpolado).
print("valor estimado:",y_interp)

valor estimado: 0.75


In [13]:
# Importa la librería numpy para operaciones numéricas.
import numpy as np

# Define el array de valores de entrada x.
x = np.array([1,2,3])
# Define el array de valores de salida y.
y = np.array([1,4,9])

# Define la función `lagrange` para realizar la interpolación de Lagrange.
def lagrange(x_data, y_data, x_val):
    # Obtiene el número de puntos de datos.
    n = len(x_data)
    # Inicializa el resultado del polinomio interpolador.
    resultado = 0

    # Bucle principal para sumar los términos del polinomio de Lagrange.
    for i in range(n):
        # Inicializa el término L_i(x) (polinomio base de Lagrange).
        L = 1

        # Bucle para calcular el producto dentro de cada término L_i(x).
        for j in range(n):
            # Excluye el caso cuando i es igual a j.
            if j != i:
                # Multiplica los factores (x_val - x_j) / (x_i - x_j).
                L *= (x_val - x_data[j]) / (x_data[i] - x_data[j])

        # Suma el término y_i * L_i(x) al resultado total.
        resultado += y_data[i] * L

    # Retorna el valor interpolado.
    return resultado

# Llama a la función `lagrange` para interpolar en x_val = 2.5.
valor = lagrange(x, y, 2.5)
# Imprime el valor interpolado.
print("Valor interpolado:", valor)


Valor interpolado: 6.25


In [14]:
# Importa la librería numpy para operaciones numéricas.
import numpy as np

# Define una función simple f(x) = x^2.
def f(x):
  return x**2

# Define el array de valores de entrada x.
x = np.array([1,2,3])
# Calcula los valores de y aplicando la función f a cada elemento de x.
y = f(x)

# Define la función `lagrange` para realizar la interpolación de Lagrange.
def lagrange(x_data,y_data,x_val):
  # Obtiene el número de puntos de datos.
  n = len(x_data)
  # Inicializa el resultado del polinomio interpolador.
  resultado = 0

  # Bucle principal para sumar los términos del polinomio de Lagrange.
  for i in range(n):
        # Inicializa el término L_i(x).
        L = 1

        # Bucle para calcular el producto dentro de cada término L_i(x).
        for j in range(n):
            # Excluye el caso cuando i es igual a j.
            if j != i:
                # Multiplica los factores (x_val - x_j) / (x_i - x_j).
                L *= (x_val - x_data[j]) / (x_data[i] - x_data[j])

        # Suma el término y_i * L_i(x) al resultado total.
        resultado += y_data[i] * L

  # Retorna el valor interpolado.
  return resultado

# Define el punto en el que se desea interpolar.
x_test = 2.5

# Calcula el valor interpolado usando la función de Lagrange.
interp = lagrange(x,y,x_test)

# Calcula el valor real de la función en x_test.
real = f(x_test)

# Calcula el error absoluto entre el valor real y el interpolado.
error = abs(real - interp)

# Imprime el valor interpolado.
print("interpolado:",interp)
# Imprime el valor real.
print("real:",real)
# Imprime el error absoluto.
print("error:",error)


interpolado: 6.25
real: 6.25
error: 0.0


In [15]:
# Importa la librería numpy para operaciones numéricas.
import numpy as np

# Define el array de valores de entrada x.
x = np.array([0, 1, 2 , 3])
# Define el array de valores de salida y.
y = np.array([1, 3, 2, 5])

# Define la función `lagrange` para realizar la interpolación de Lagrange.
def lagrange(x_data, y_data, x_val):
    # Obtiene el número de puntos de datos.
    n = len(x_data)
    # Inicializa el resultado del polinomio interpolador.
    resultado = 0

    # Bucle principal para sumar los términos del polinomio de Lagrange.
    for i in range(n):
        # Inicializa el término L_i(x).
        L = 1

        # Bucle para calcular el producto dentro de cada término L_i(x).
        for j in range(n):
            # Excluye el caso cuando i es igual a j.
            if i != j:
                # Multiplica los factores (x_val - x_j) / (x_i - x_j).
                L *= (x_val - x_data[j]) / (x_data[i] - x_data[j])

        # Suma el término y_i * L_i(x) al resultado total.
        resultado += y_data[i] * L

    # Retorna el valor interpolado.
    return resultado

# Define el punto en el que se desea interpolar.
x_interp = 1.5
# Llama a la función `lagrange` para obtener el valor interpolado.
y_interp = lagrange(x, y, x_interp)
# Imprime el valor estimado (interpolado).
print("Valor estimado", y_interp)

Valor estimado 2.4375


In [16]:
# Importa la librería numpy para operaciones numéricas.
import numpy as np
# Importa CubicSpline de scipy.interpolate para interpolación por splines cúbicos.
from scipy.interpolate import CubicSpline

# Define el array de valores de entrada x.
x = np.array([0,1,2,3])
# Define el array de valores de salida y.
y = np.array([1,3,2,5])

# Crea un objeto CubicSpline usando los puntos de datos x e y.
spline = CubicSpline(x,y)

# Genera un array de 100 puntos igualmente espaciados entre 0 y 3 para la interpolación.
x_interp = np.linspace(0,3,100)
# Evalúa el spline cúbico en los nuevos puntos x_interp para obtener los valores interpolados y_interp.
y_interp = spline(x_interp)

# Imprime los valores interpolados.
print("valores interpolados:",y_interp)

valores interpolados: [1.         1.17220877 1.33542959 1.48985725 1.63568653 1.77311221
 1.90232908 2.02353192 2.13691553 2.24267468 2.34100416 2.43209877
 2.51615327 2.59336246 2.66392112 2.72802404 2.78586601 2.8376418
 2.88354621 2.92377401 2.95852    2.98797896 3.01234568 3.03181494
 3.04658152 3.05684021 3.0627858  3.06461307 3.06251681 3.0566918
 3.04733283 3.03463468 3.01879215 3.         2.97845303 2.95434603
 2.92787378 2.89923106 2.86861266 2.83621337 2.80222797 2.76685125
 2.73027799 2.69270297 2.65432099 2.61532682 2.57591526 2.53628108
 2.49661908 2.45712404 2.41799074 2.37941397 2.34158852 2.30470917
 2.2689707  2.2345679  2.20169556 2.17054846 2.14132139 2.11420913
 2.08940646 2.06710818 2.04750907 2.03080391 2.01718749 2.00685459
 2.         1.99681851 1.99750489 2.00225394 2.01126045 2.02471918
 2.04282494 2.06577251 2.09375667 2.1269722  2.1656139  2.20987654
 2.25995492 2.31604382 2.37833802 2.44703231 2.52232147 2.60440029
 2.69346356 2.78970606 2.89332257 3.004507

In [17]:
# Importa la librería numpy para operaciones numéricas.
import numpy as np

# Define el array de valores de entrada x.
x = np.array([1,2,3,4,5])
# Define el array de valores de salida y.
y = np.array([2,4,5,4,5])

# Realiza un ajuste polinómico de grado 1 (regresión lineal) a los datos x e y.
# 'coef' contendrá la pendiente (m) y el intercepto (b).
coef = np.polyfit(x,y,1)

# Extrae la pendiente (m) del resultado.
m = coef[0]
# Extrae el intercepto (b) del resultado.
b = coef[1]

# Calcula los valores de y predichos usando la ecuación de la línea (y = mx + b).
y_pred = m*x + b

# Imprime la pendiente.
print("pendiente:",m)
# Imprime el intercepto.
print("intercepto:",b)
# Imprime los valores predichos de y.
print("prediccion:",y_pred)

pendiente: 0.6000000000000001
intercepto: 2.1999999999999997
prediccion: [2.8 3.4 4.  4.6 5.2]


In [18]:
# Importa la librería numpy para operaciones numéricas.
import numpy as np

# Define el array de valores de entrada x.
x = np.array([1,2,3,4,5])
# Define el array de valores de salida y.
y = np.array([2,4,5,4,5])

# Calcula la matriz de coeficientes de correlación de Pearson entre x e y.
# [0,1] accede al coeficiente de correlación entre el primer y segundo array (x e y).
correlacion = np.corrcoef(x,y)[0,1]

# Imprime el coeficiente de correlación.
print("coeficiente de correlacion:",correlacion)

coeficiente de correlacion: 0.7745966692414834
